# Dependencies
#markdown:         redcarpet
markdown:       kramdown       
highlighter:      pygments

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
    #  - jekyll-mentions
  - jekyll-paginate
    #  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
    #  - jekyll-mentions
  #- jekyll-paginate
    #  - jekyll-redirect-from

# Permalinks
permalink:        pretty

#gems: [jekyll-paginate]
#paginate: 5
#paginate_path: "page:num"

# Setup
fname:            Akshay 
lname:            P Guptha
title:            Akshay Paniraja Guptha
tagline:          'My portfolio'
url:              https://akshaypguptha.github.io
baseurl:          /

